language: "python"
os:
  "ubuntu"

dist: "xenial"
sudo: true
python:
    "3.8.2"

env:
    "global":

      "PIPENV_VENV_IN_PROJECT": "1"


      "PIPENV_IGNORE_VIRTUALENVS": "1"



install:
    "pip install -r requirements.txt"

script: 
    "flake8"

