language: python
dist: xenial
sudo: true

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
dependencias:
  certifi==2020.4.5.1
  chardet==3.0.4
  idna==2.9
  requests==2.23.0
  urllib3==1.25.9
